name: Deploy Smart Expense Tracker Lambdas

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy Lambda Functions
    runs-on: ubuntu-latest

    steps:
      # 1. Get the code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Authenticate GitHub Actions with AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::669828370396:role/GitHubActions-SmartExpenseTracker
          aws-region: ap-south-1

      # 3. Deploy Add Lambda
      - name: Deploy SmartExpenseAdd
        run: |
          cd lambdas/add
          zip lambda.zip lambda_function.py
          aws lambda update-function-code \
            --function-name SmartExpenseAdd \
            --zip-file fileb://lambda.zip

      # 4. Deploy Get Lambda
      - name: Deploy SmartExpenseGet
        run: |
          cd lambdas/get
          zip lambda.zip lambda_function.py
          aws lambda update-function-code \
            --function-name SmartExpenseGet \
            --zip-file fileb://lambda.zip

      # 5. Deploy Delete Lambda
      - name: Deploy SmartExpenseDelete
        run: |
          cd lambdas/delete
          zip lambda.zip lambda_function.py
          aws lambda update-function-code \
            --function-name SmartExpenseDelete \
            --zip-file fileb://lambda.zip

      # 6. Deploy Stats Lambda
      - name: Deploy SmartExpenseStats
        run: |
          cd lambdas/stats
          zip lambda.zip lambda_function.py
          aws lambda update-function-code \
            --function-name SmartExpenseStats \
            --zip-file fileb://lambda.zip
